# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 07:44
from __future__ import unicode_literals

from django.db import migrations
from django.template.defaultfilters import slugify


def update_slugs(apps, schema_editor):
    Team = apps.get_model('users', 'Team')
    for team in Team.objects.all():
        team.slug = slugify(team.name)
        team.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_team_slug'),
    ]

    operations = [
        migrations.RunPython(update_slugs),
    ]
