# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskentry',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='task',
            name='plan_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='plan_start',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
