# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskentry',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tasks.Task'),
        ),
    ]
