# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 07:54
from __future__ import unicode_literals

from django.db import migrations
from django.template.defaultfilters import slugify


def update_slugs(apps, schema_editor):
    Project = apps.get_model('tasks', 'Project')
    for project in Project.objects.all():
        project.slug = slugify(project.name)
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_project_slug'),
    ]

    operations = [
        migrations.RunPython(update_slugs),
    ]
