# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20170617_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
