# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20170617_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='plan_end',
        ),
        migrations.RemoveField(
            model_name='task',
            name='plan_start',
        ),
        migrations.AddField(
            model_name='task',
            name='phase',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Phase'),
        ),
    ]
