# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 10:04
from __future__ import unicode_literals

from django.db import migrations


def migrate_phase(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    Phase = apps.get_model('tasks', 'Phase')

    for task in Task.objects.all():
        project = task.project
        phase = None
        if project.phase_set.count() > 0:
            phase = project.phase_set.all()[0]
        else:
            phase = Phase(name="Historical", project=project)
            phase.save()

        task.phase = phase
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20170628_1004'),
    ]

    operations = [
        migrations.RunPython(migrate_phase),
    ]
