# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20170628_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
