# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_phase_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phase',
            old_name='start_date',
            new_name='start_time',
        ),
    ]
