# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20170628_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ['-start_time']},
        ),
    ]
